# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: morse_symbol.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'morse_symbol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12morse_symbol.proto\"\x89\x01\n\x0bMorseSymbol\x12#\n\x06symbol\x18\x01 \x01(\x0e\x32\x13.MorseSymbol.Symbol\x12\x11\n\tfrequency\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\"/\n\x06Symbol\x12\x07\n\x03\x44IT\x10\x00\x12\x07\n\x03\x44\x41H\x10\x01\x12\t\n\x05\x42REAK\x10\x02\x12\x08\n\x04WORD\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'morse_symbol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MORSESYMBOL']._serialized_start=23
  _globals['_MORSESYMBOL']._serialized_end=160
  _globals['_MORSESYMBOL_SYMBOL']._serialized_start=113
  _globals['_MORSESYMBOL_SYMBOL']._serialized_end=160
# @@protoc_insertion_point(module_scope)
